### PR TITLE
Adds support for bridging Ant+ Heart Rate measurements to Bluetooth

### PR DESCRIPTION
**Pull request by pinkemma**
Adds support for receiving Ant+ Heart Rate measurements and bridges this to Bluetooth.

The HR is also shown on screen along with Speed and Cadence.

This code has been tested with a Garmin Fenix 5S with Broadcast mode on, to a Samsung Galaxy S9.

I have tried to adhere to your coding style as much as possible.

### CODE REVIEW

**Comment by starryalley** [comment]
Awesome! You've done this! 
I didn't do it in the first place because I've got an old bluetooth/ANT+ heart rate monitor already so I have no urge to write it. But I do have a ANT+ only Garmin heart rate monitor which I'm going to test with this great PR during the weekend!

Thanks :)

**Comment by pinkemma** [comment]
Thank 🥇 YOU 🥇 for this project! Your code is also very nice and really easy to work with. 

I see you have a TODO to be able to toggle services on and off, I might see if I have time to tackle this, as well.

Getting all my data into Zwift is very nice :)

**Comment by starryalley** [comment]
It just works :) Thanks so much!

**Comment by pinkemma** [comment]
You're welcome!

I noticed that I cannot get the power and cadence from my Wahoo Kickr Core. I'll will have a look to see if this can be fixed (I guess more for completeness sake, since it also outputs BT, but hey!).

Thank you for being a gracious host!

**Pull request merged**
