### PR TITLE
Added support for long-holding on a sensor name to rescan

### PR DESCRIPTION
**Pull request by pinkemma**
Creates bindings to support long pressing sensor names to rescan for the sensor. This allows for rescanning a device if the search has timed out, or otherwise lost connecting since starting.

This version uses lambdas to avoid code duplication, so also sets the Java version to 1.8.

The initialization of the various sensor searches has also been refactored into their own functions, so they can be reused for restarting the scan.

### CODE REVIEW

**Comment by pinkemma** [comment]
This pull request seems to have pulled later changes that add an icon to the notification area so clicking the notification brings up the all (and some tweaking the notification creation). I assumed a pull request would only act on anything up until the PR is created, not so it seems!

I kind of forgot about hacktoberfest due to real life obligations, so cutting it close ;) The time it was submitted, not accepted, is the deadline afaik.

**Comment by starryalley** [comment]
Sorry @pinkemma I completely forgot to check this PR until now! Was too busy with other stuff during the past 2-3 weeks. I'll check and merge ASAP!

**Comment by starryalley** [comment]
Thanks @pinkemma for this wonderful PR

**Comment by pinkemma** [comment]
I hope you (and others!) find the changes helpful! I definitely do, I use it 3-5 times a week! Thank you again for this app. 

Also, as a bonus, I'm experiencing less connectivity drop because the phone usually is half-way between the PC and the trainer, giving it a lil boost.

**Pull request merged**
